name: Daily run
on:
  schedule:
    - cron: "5 13 * * *"
  push:
    branches:
      - main
env:
  GROUP_CHAT_ID: ${{ secrets.GROUP_CHAT_ID }}
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: 📁 Check out repository
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v3.1.4
        with:
          python-version: 3.x

      - name: 🛠️ Update system
        run: ./install.sh

      - name: ⚙️ Install python dependencies
        run: pip install -r requirements.txt

      - name: 🚀 Run
        run: python main.py
        
      - name: 🔮 COMPLETED!
        run: |
          dt=$(date '+%d/%m/%Y %H:%M:%S');
          echo "COMPLETED AT $dt"
        
