name: fast-unit-test
on: 
  pull_request:
    branches: [ master, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: 📂 checkout front repo
        uses: actions/checkout@v3
        
      - name: run
        run: ./install.sh
